# Generated by Django 3.2.13 on 2022-06-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0005_alter_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
