# Generated by Django 3.2.13 on 2022-06-16 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0006_remove_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jp_app.recruiter'),
            preserve_default=False,
        ),
    ]
